name = "tolak-me"
type = "javascript"
workers_dev = true
compatibility_date = "2022-07-17"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# [site]
# bucket = "./public"

# kv_namespaces = [ 
#   { binding = "TOLAK-KV", preview_id = "b89efd9681de43c8803fa2179328f539", id = "b89efd9681de43c8803fa2179328f539" }
# ]

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
